const data = [
    {
        id: 1,
        title: 'Barry Lyndon',
        image: 'https://a.ltrbxd.com/resized/sm/upload/0f/r6/bn/w7/x2JQCgLjieWOwvImeGtLmuNgsrq-0-2000-0-3000-crop.jpg?v=9c250ee969',
        subtitle: "AT LONG LAST REDMOND BARRY BECAME A GENTLEMAN—AND THAT WAS HIS TRAGEDY.",
        description: 'An Irish rogue uses his cunning and wit to work his way up the social classes of 18th century England, transforming himself from the humble Redmond Barry into the noble Barry Lyndon.',
        favorite: false,
        ratings: 5,
        year: 1975,
        director: 'Stanley Kubrick',
        like: '287K',
        dislike: '2K'
    },
    {
        id: 2,
        title: 'The Godfather',
        image: 'https://a.ltrbxd.com/resized/film-poster/5/1/8/1/8/51818-the-godfather-0-2000-0-3000-crop.jpg?v=bca8b67402',
        subtitle: "AN OFFER YOU CAN’T REFUSE.",
        description: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
        favorite: false,
        ratings: 5,
        year: 1972,
        director: 'Francis Ford Coppola',
        like: '330K',
        dislike: '9K'
    },
    {
        id: 3,
        title: 'GoodFellas',
        image: 'https://a.ltrbxd.com/resized/film-poster/5/1/3/8/3/51383-goodfellas-0-2000-0-3000-crop.jpg?v=c6c265f228',
        subtitle: 'THREE DECADES OF LIFE IN THE MAFIA.',
        description: 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
        favorite: false,
        ratings: 4.8,
        year: 1990,
        director: 'Martin Scorsese',
        like: '330K',
        dislike: '9K'
    },
    {
        id: 4,
        title: 'The Deer Hunter',
        image: 'https://a.ltrbxd.com/resized/sm/upload/16/v3/46/iu/slNJESItHPqp1CENEJQUPw8d7WE-0-2000-0-3000-crop.jpg?v=55162bb367',
        subtitle: '',
        description: 'A group of working-class friends decides to enlist in the Army during the Vietnam War and finds it to be hellish chaos – not the noble venture they imagined. Before they left, Steven married his pregnant girlfriend – and Michael and Nick were in love with the same woman. But all three are different men upon their return.',
        favorite: false,
        ratings: 4.5,
        year: 1978,
        director: 'Michael Cimino',
        like: '261K',
        dislike: '72K'
    },
    {
        id: 5,
        title: 'Civil War',
        image: 'https://a.ltrbxd.com/resized/film-poster/8/3/4/6/5/6/834656-civil-war-0-2000-0-3000-crop.jpg?v=aefec33dbe',
        subtitle: 'WELCOME TO THE FRONTLINE.',
        description: 'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.',
        favorite: false,
        ratings: 3.5,
        year: 2024,
        director: 'Alex Garland',
        like: '419K',
        dislike: '132K'
    },
    {
        id: 6,
        title: 'Dune: Part Two',
        image: 'https://a.ltrbxd.com/resized/film-poster/6/1/7/4/4/3/617443-dune-part-two-0-2000-0-3000-crop.jpg?v=cc533700f8',
        subtitle: 'LONG LIVE THE FIGHTERS.',
        description: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
        favorite: false,
        ratings: 4.5,
        year: 2024,
        director: 'Denis Villeneuve',
        like: '1.6M',
        dislike: '21K'
    },
    {
        id: 7,
        title: 'Napoleon',
        image: 'https://a.ltrbxd.com/resized/film-poster/6/7/4/1/3/7/674137-napoleon-0-2000-0-3000-crop.jpg?v=8cb54e07b5',
        subtitle: 'HE CAME FROM NOTHING. HE CONQUERED EVERYTHING.',
        description: 'An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.',
        favorite: false,
        ratings: 2.5,
        year: 2023,
        director: 'Ridley Scott',
        like: '421K',
        dislike: '300K'
    },
    {
        id: 8,
        title: 'The Promised Land',
        image: 'https://a.ltrbxd.com/resized/film-poster/8/8/2/3/0/7/882307-the-promised-land-0-2000-0-3000-crop.jpg?v=c5a8a9a665',
        subtitle: 'Bastarden',
        description: 'In 18th century Denmark, Captain Ludvig Kahlen — a proud, ambitious, but impoverished war hero — sets out to tame a vast, uninhabitable land on which seemingly nothing can grow. He seeks to start farming crops, build a colony in the name of the King, and gain a noble title for himself. This beautiful but forbidding area also happens to be under the rule of the merciless Frederik De Schinkel, a preening nobleman who realizes the threat Kahlen represents to his power.',
        favorite: false,
        ratings: 4,
        year: 2023,
        director: 'Nikolaj Arcel',
        like: '33K',
        dislike: '1K'
    },
    {
        id: 9,
        title: 'Oppenheimer',
        image: 'https://a.ltrbxd.com/resized/film-poster/7/8/4/3/2/8/784328-oppenheimer-0-2000-0-3000-crop.jpg?v=e3c6e7a32c',
        subtitle: 'THE WORLD FOREVER CHANGES.',
        description: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.',
        favorite: false,
        ratings: 5,
        year: 2023,
        director: 'Christopher Nolan',
        like: '2.6M',
        dislike: '217K'
    },
    {
        id: 10,
        title: 'Evil Dead Rise',
        image: 'https://a.ltrbxd.com/resized/film-poster/6/3/6/7/6/1/636761-evil-dead-rise-0-2000-0-3000-crop.jpg?v=51a7fe0b29',
        subtitle: 'MOMMY LOVES YOU TO DEATH.',
        description: 'Three siblings find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.',
        favorite: false,
        ratings: 3.5,
        year: 2023,
        director: 'Lee Cronin',
        like: '569K',
        dislike: '147K'
    },
    {
        id: 11,
        title: 'Shazam! Fury of the Gods',
        image: 'https://a.ltrbxd.com/resized/film-poster/5/2/2/4/0/5/522405-shazam-fury-of-the-gods-0-2000-0-3000-crop.jpg?v=6f53eef30f',
        subtitle: 'OH. MY. GODS.',
        description: 'Billy Batson and his foster siblings, who transform into superheroes by saying “Shazam!”, are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
        favorite: false,
        ratings: 2.5,
        year: 2023,
        director: 'David F. Sandberg',
        like: '248K',
        dislike: '78K'
    },
    {
        id: 12,
        title: 'John Wick: Chapter 4',
        image: 'https://a.ltrbxd.com/resized/film-poster/5/3/0/8/8/2/530882-john-wick-chapter-4-0-2000-0-3000-crop.jpg?v=bc32219057',
        subtitle: 'NO WAY BACK, ONE WAY OUT.',
        description: 'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
        favorite: false,
        ratings: 4,
        year: 2023,
        director: 'Chad Stahelski',
        like: '756K',
        dislike: '263K'
    },
    {
        id: 13,
        title: 'Black Adam',
        image: 'https://a.ltrbxd.com/resized/film-poster/3/6/9/1/7/9/369179-black-adam-0-2000-0-3000-crop.jpg?v=5e1791e3fa',
        subtitle: 'THE WORLD NEEDED A HERO. IT GOT BLACK ADAM.',
        description: 'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
        favorite: false,
        ratings: 2.5,
        year: 2023,
        director: 'Jaume Collet-Serra',
        like: '88K',
        dislike: '53K'
    },
    {
        id: 14,
        title: 'All Quiet on the Western Front',
        image: 'https://a.ltrbxd.com/resized/film-poster/1/6/5/3/0/16530-all-quiet-on-the-western-front-0-2000-0-3000-crop.jpg?v=bff4d496a1',
        subtitle: 'Im Westen nichts Neues',
        description: 'Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.',
        favorite: false,
        ratings: 4,
        year: 2023,
        director: 'Jaume Collet-Serra',
        like: '88K',
        dislike: '53K'
    },
    {
        id: 15,
        title: 'Pulp Fiction',
        image: 'https://a.ltrbxd.com/resized/film-poster/5/1/4/4/4/51444-pulp-fiction-0-2000-0-3000-crop.jpg?v=dee19a8077',
        subtitle: 'JUST BECAUSE YOU ARE A CHARACTER DOESN’T MEAN YOU HAVE CHARACTER.',
        description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
        favorite: false,
        ratings: 4.8,
        year: 1994,
        director: 'Quentin Tarantino',
        like: '1.1M',
        dislike: '25K'
    },
    {
        id: 16,
        title: 'The Dark Knight',
        image: 'https://a.ltrbxd.com/resized/sm/upload/78/y5/zg/ej/oefdD26aey8GPdx7Rm45PNncJdU-0-2000-0-3000-crop.jpg?v=2d0ce4be25',
        subtitle: 'WELCOME TO A WORLD WITHOUT RULES.',
        description: 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        favorite: false,
        ratings: 5,
        year: 2008,
        director: 'Christopher Nolan',
        like: '2.5M',
        dislike: '50K'
    },
    {
        id: 17,
        title: 'Schindler\'s List',
        image: 'https://a.ltrbxd.com/resized/sm/upload/bz/1x/em/jr/yPisjyLweCl1tbgwgtzBCNCBle-0-2000-0-3000-crop.jpg?v=ca5215c5a9',
        subtitle: 'WHOEVER SAVES ONE LIFE, SAVES THE WORLD ENTIRE.',
        description: 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
        favorite: false,
        ratings: 4.9,
        year: 1993,
        director: 'Steven Spielberg',
        like: '700K',
        dislike: '12K'
    },
    {
        id: 18,
        title: 'The Shawshank Redemption',
        image: 'https://a.ltrbxd.com/resized/sm/upload/7l/hn/46/uz/zGINvGjdlO6TJRu9wESQvWlOKVT-0-2000-0-3000-crop.jpg?v=8736d1c395',
        subtitle: 'FEAR CAN HOLD YOU PRISONER. HOPE CAN SET YOU FREE.',
        description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        favorite: false,
        ratings: 5,
        year: 1994,
        director: 'Frank Darabont',
        like: '2.3M',
        dislike: '40K'
    },
    {
        id: 19,
        title: 'Inception',
        image: 'https://a.ltrbxd.com/resized/sm/upload/sv/95/s9/4j/inception-0-2000-0-3000-crop.jpg?v=30d7224316',
        subtitle: 'YOUR MIND IS THE SCENE OF THE CRIME.',
        description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        favorite: false,
        ratings: 4.7,
        year: 2010,
        director: 'Christopher Nolan',
        like: '2M',
        dislike: '60K'
    },
    {
        id: 20,
        title: 'The Matrix',
        image: 'https://a.ltrbxd.com/resized/film-poster/5/1/5/1/8/51518-the-matrix-0-2000-0-3000-crop.jpg?v=fc7c366afe',
        subtitle: 'WELCOME TO THE REAL WORLD.',
        description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        favorite: false,
        ratings: 4.8,
        year: 1999,
        director: 'Lana Wachowski, Lilly Wachowski',
        like: '1.8M',
        dislike: '30K'
    },
    {
        id: 21,
        title: 'Forrest Gump',
        image: 'https://a.ltrbxd.com/resized/film-poster/2/7/0/4/2704-forrest-gump-0-2000-0-3000-crop.jpg?v=173bc04cf0',
        subtitle: 'LIFE IS LIKE A BOX OF CHOCOLATES... YOU NEVER KNOW WHAT YOU\'RE GONNA GET.',
        description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
        favorite: false,
        ratings: 4.9,
        year: 1994,
        director: 'Robert Zemeckis',
        like: '3.5M',
        dislike: '75K'
    },
    {
        id: 22,
        title: 'The Silence of the Lambs',
        image: 'https://a.ltrbxd.com/resized/film-poster/5/1/7/8/2/51782-the-silence-of-the-lambs-0-2000-0-3000-crop.jpg?v=18d88bdff4',
        subtitle: 'TO ENTER THE MIND OF A KILLER, SHE MUST CHALLENGE THE MIND OF A MADMAN.',
        description: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
        favorite: false,
        ratings: 4.9,
        year: 1991,
        director: 'Jonathan Demme',
        like: '2.6M',
        dislike: '40K'
    },
    {
        id: 23,
        title: 'Gladiator',
        image: 'https://a.ltrbxd.com/resized/film-poster/5/1/9/5/2/51952-gladiator-0-2000-0-3000-crop.jpg?v=ebc9155e73',
        subtitle: 'THE GENERAL WHO BECAME A SLAVE. THE SLAVE WHO BECAME A GLADIATOR. THE GLADIATOR WHO DEFIED AN EMPIRE.',
        description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
        favorite: false,
        ratings: 4.7,
        year: 2000,
        director: 'Ridley Scott',
        like: '1.9M',
        dislike: '60K'
    },
    {
        id: 24,
        title: 'The Departed',
        image: 'https://a.ltrbxd.com/resized/sm/upload/jr/th/pu/pb/laefkgrfa3oKwvBtWTBtf2suiI4-0-2000-0-3000-crop.jpg?v=f5d8231026',
        subtitle: 'LIES. BETRAYAL. SACRIFICE. HOW FAR WILL YOU TAKE IT?',
        description: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
        favorite: false,
        ratings: 4.8,
        year: 2006,
        director: 'Martin Scorsese',
        like: '2.1M',
        dislike: '30K'
    },
    { id: 25,
        title: 'Seven Samurai',
        image: 'https://a.ltrbxd.com/resized/sm/upload/ji/5q/0k/rv/v6xrz4fr92KY1oNC3HsEvrsvR1n-0-2000-0-3000-crop.jpg?v=973d70bb0c',
        subtitle: 'THE GREATEST FILM OF ALL TIME!',
        description: 'A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.',
        favorite: false,
        ratings: 4.8,
        year: 1954,
        director: 'Akira Kurosawa',
        like: '1.6M',
        dislike: '10K'
    },
    {
        id: 26,
        title: 'The Lord of the Rings: The Return of the King',
        image: 'https://a.ltrbxd.com/resized/sm/upload/zs/nt/u4/uz/xieWkPAgQrrk5wOyncayPd65hrp-0-2000-0-3000-crop.jpg?v=4c89d05285',
        subtitle: 'THE EYE OF THE ENEMY IS MOVING.',
        description: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
        favorite: false,
        ratings: 4.9,
        year: 2003,
        director: 'Peter Jackson',
        like: '6M',
        dislike: '50K'
    },
    {
        id: 27,
        title: 'Blade Runner',
        image: 'https://a.ltrbxd.com/resized/sm/upload/85/io/38/dz/vfzE3pjE5G7G7kcZWrA3fnbZo7V-0-2000-0-3000-crop.jpg?v=0d5de70f0d',
        subtitle: 'A FUTURE NO ONE IMAGINED. A LOVE NO ONE EXPECTED.',
        description: 'In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.',
        favorite: false,
        ratings: 4.5,
        year: 1982,
        director: 'Ridley Scott',
        like: '502K',
        dislike: '36K'
    },
    {
        id: 28,
        title: 'The Usual Suspects',
        image: 'https://a.ltrbxd.com/resized/film-poster/5/1/4/9/5/51495-the-usual-suspects-0-2000-0-3000-crop.jpg?v=c02dce5b81',
        subtitle: 'WHO IS KEYSER SÖZE?',
        description: 'Held in an L.A. interrogation room, Verbal Kint attempts to convince the feds that the mythic crime lord not only exists, but was also responsible for drawing him and his four partners into a multi-million dollar heist that ended with an explosion in San Pedro Harbor – leaving few survivors.',
        favorite: false,
        ratings: 4.8,
        year: 1995,
        director: 'Bryan Singer',
        like: '900K',
        dislike: '42K'
    },
    {
        id: 29,
        title: 'The Prestige',
        image: 'https://a.ltrbxd.com/resized/film-poster/5/1/1/4/7/51147-the-prestige-0-2000-0-3000-crop.jpg?v=ad7e891177',
        subtitle: 'ARE YOU WATCHING CLOSELY?',
        description: 'A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for suprmaecy -- to create the ultimate illusion.',
        favorite: false,
        ratings: 4.8,
        year: 2006,
        director: 'Christopher Nolan',
        like: '1.1M',
        dislike: '71K'
    },
    {
        id: 30,
        title: 'Harakiri',
        image: 'https://a.ltrbxd.com/resized/film-poster/4/3/0/1/5/43015-harakiri-0-2000-0-3000-crop.jpg?v=007080a0fb',
        subtitle: 'THE WORLD HAS NEVER UNDERSTOOD WHY THE JAPANESE PREFER DEATH TO DISHONOR!',
        description: 'Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end.',
        favorite: false,
        ratings: 5,
        year: 1962,
        director: 'Masaki Kobayashi',
        like: '138K',
        dislike: '62K'
    }
]

export default data